services:
  backend:
    container_name: postgres-backend
    image: node:18
    volumes:
      - .:/workdir
    working_dir: /workdir
    ports:
      - 3000:3000
    command: >
      bash -c "
        npm install &&
        npm run generate &&
        npm run prisma:generate &&
        npm run dev
      "
  db:
    container_name: postgres-database
    image: postgres:15
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres